# Rutherford Scattering simulation

## Constants

In [61]:
# atomic properties
m_p = 938.272 # MeV/c^2
m_n = 939.565 # MeV/c^2
m_a = 2*m_p + 2*m_n
A_a = 4
Z_a = 2

# geometry
source_x = 0
source_y = 0
source_z = 0

## Particle

In [72]:
import numpy as np

In [92]:
class Particle():
    def __init__(self, source, E_k, M, N=1):
        self.source = source
        particles = source.GenerateParticle(E_k, M, N)
        self.particle_x = particles[1][:,0]
        self.particle_y = particles[1][:,1]
        self.particle_z = particles[1][:,2]
        self.particle_px = particles[4][:,0]
        self.particle_py = particles[4][:,1]
        self.particle_pz = particles[4][:,2]
    
    def FreeEvolution(self):
        pass
    
    def TimeEvolution(self, F, dt):
        # x_(i+1) = x_i + t_i*px_i/M
        # px_(i+1) = px_i + F_i*t_i
        pass

In [82]:
particles = Particle(source, 4.8, m_a)

In [93]:
particles.particle_x

array([-0.56097916])

## Source

In [27]:
import numpy as np

In [88]:
class Source():
    def __init__(self, s_x, s_y, s_z, s_r, s_a):
        self.source_x = s_x    # x position
        self.source_y = s_y    # y position
        self.source_z = s_z    # z position
        self.source_r = s_r    # radius
        self.source_a = s_a    # activity

    def GenerateParticle(self, E_k, M, N=1):
        # kinematics
        gamma = 1.0 + E_k/M
        beta  = np.sqrt(1 - 1/(gamma*gamma))
        p     = M * gamma * beta
        
        # source point of emission (polar coordinates)
        r_s = np.sqrt(np.random.uniform(0, 1, size=(N,1))) * self.source_r
        t_s = np.random.uniform(0, 1, size=(N,1)) * 2 * np.pi
        
        # source point of emission (carthesian coordinates)
        x_s = self.source_x + r_s * np.cos(t_s)
        y_s = self.source_y + r_s * np.sin(t_s)
        z_s = self.source_z * np.ones((N,1))
        
        # versor of direction (polar coordinates)
        u_pp = np.random.uniform(0, 1, size=(N,1)) * 2 * np.pi             # momentum: phi
        u_pt = np.arccos(2 * np.random.uniform(0, 1, size=(N,1)) - 1.0)    # momentum: theta
        
        # versor of direction (carthesian coordinates)
        u_px = np.cos(u_pp)*np.sin(u_pt)    # momentum : x
        u_py = np.sin(u_pp)*np.sin(u_pt)    # momentum : y
        u_pz = np.cos(u_pt)                 # momentum : z
        
        # momentum of alphas (carthesian coordinates)
        px = u_px * p
        py = u_py * p
        pz = u_pz * p
        
        return [np.hstack((r_s,t_s)),
                np.hstack((x_s,y_s,z_s)),
                np.hstack((r_s,t_s)),
                np.hstack((u_px,u_py,u_pz)),
                np.hstack((px,py,pz))]

In [89]:
source = Source(0,0,0,1,300)

In [90]:
source.GenerateParticle(4.8, m_a, 1)

[array([[0.93135976, 0.98343305]]),
 array([[0.5161299, 0.7752683, 0.       ]]),
 array([[0.93135976, 0.98343305]]),
 array([[-0.17832655,  0.97909839, -0.09780588]]),
 array([[-33.87148883, 185.97073846, -18.57732712]])]

In [17]:
a = np.ones((1,3))
b = np.ones((1,3))
print(a,b)
c = np.vstack((a,b))
c

[[1. 1. 1.]] [[1. 1. 1.]]


array([[1., 1., 1.],
       [1., 1., 1.]])

## Collimator

In [ ]:
import numpy as np

In [ ]:
class Collimator():
    def __init__(self, c_x, c_y, c_z, c_w, c_h):
        self.collimator_x = c_x    # x origin    +++++
        self.collimator_y = c_y    # y origin    +   +
        self.collimator_z = c_z    # z origin    o++++
        self.collimator_w = c_w    # width
        self.collimator_h = c_h    # height